import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Heeader from './components/header';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Web SyH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="">
        <Heeader/>
        <div className="mt-16">
        {children}
        </div>
        </main>
        </body>
    </html>
  );
}
