import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Heeader from './components/dashboard/header';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Web SyH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className  }>
        <Heeader/>
        {children}</body>
    </html>
  );
}
