-- CreateTable
CREATE TABLE `articulo` (
    `codigo` VARCHAR(254) NULL,
    `grupo` VARCHAR(254) NULL,
    `subgrupo` VARCHAR(254) NULL,
    `nombre` VARCHAR(254) NULL,
    `nombrecorto` VARCHAR(254) NULL,
    `referencia` VARCHAR(254) NULL,
    `marca` VARCHAR(254) NULL,
    `unidad` VARCHAR(254) NULL,
    `usaexist` DOUBLE NULL,
    `costo` DOUBLE NULL,
    `precio1` DOUBLE NULL,
    `precio2` DOUBLE NULL,
    `precio3` DOUBLE NULL,
    `precio4` DOUBLE NULL,
    `precio5` DOUBLE NULL,
    `precio6` DOUBLE NULL,
    `precio7` DOUBLE NULL,
    `precio8` DOUBLE NULL,
    `preciofin1` DOUBLE NULL,
    `preciofin2` DOUBLE NULL,
    `preciofin3` DOUBLE NULL,
    `preciofin4` DOUBLE NULL,
    `preciofin5` DOUBLE NULL,
    `preciofin6` DOUBLE NULL,
    `preciofin7` DOUBLE NULL,
    `preciofin8` DOUBLE NULL,
    `existencia` DOUBLE NULL,
    `inactiva` DOUBLE NULL,
    `comprometid` DOUBLE NULL,
    `minimo` DOUBLE NULL,
    `maximo` DOUBLE NULL,
    `origen` DOUBLE NULL,
    `impuesto` DOUBLE NULL,
    `usaserial` DOUBLE NULL,
    `comision1` DOUBLE NULL,
    `comision2` DOUBLE NULL,
    `comision3` DOUBLE NULL,
    `comision4` DOUBLE NULL,
    `comision5` DOUBLE NULL,
    `comision6` DOUBLE NULL,
    `comision7` DOUBLE NULL,
    `comision8` DOUBLE NULL,
    `util1` DOUBLE NULL,
    `util2` DOUBLE NULL,
    `util3` DOUBLE NULL,
    `util4` DOUBLE NULL,
    `util5` DOUBLE NULL,
    `util6` DOUBLE NULL,
    `util7` DOUBLE NULL,
    `util8` DOUBLE NULL,
    `formato` VARCHAR(254) NULL,
    `decimales` DOUBLE NULL,
    `compuesto` DOUBLE NULL,
    `cfob` DOUBLE NULL,
    `cnacionali` DOUBLE NULL,
    `prcnac` DOUBLE NULL,
    `cflete` DOUBLE NULL,
    `prcflete` DOUBLE NULL,
    `carancel` DOUBLE NULL,
    `prcarancel` DOUBLE NULL,
    `cgastoper` DOUBLE NULL,
    `prccosoper` DOUBLE NULL,
    `cotroscos` DOUBLE NULL,
    `ccostocyf` DOUBLE NULL,
    `costoex` DOUBLE NULL,
    `costoref` DOUBLE NULL,
    `precio1ex` DOUBLE NULL,
    `precio2ex` DOUBLE NULL,
    `precio3ex` DOUBLE NULL,
    `precio4ex` DOUBLE NULL,
    `precio5ex` DOUBLE NULL,
    `precio6ex` DOUBLE NULL,
    `precio7ex` DOUBLE NULL,
    `precio8ex` DOUBLE NULL,
    `factor` DOUBLE NULL,
    `garantia` DOUBLE NULL,
    `empaque` DOUBLE NULL,
    `unidadgrp` VARCHAR(254) NULL,
    `cntgrp` DOUBLE NULL,
    `costgrp` DOUBLE NULL,
    `precio1grp` DOUBLE NULL,
    `precio2grp` DOUBLE NULL,
    `precio3grp` DOUBLE NULL,
    `precio4grp` DOUBLE NULL,
    `precio5grp` DOUBLE NULL,
    `precio6grp` DOUBLE NULL,
    `precio7grp` DOUBLE NULL,
    `precio8grp` DOUBLE NULL,
    `prcgrp1` DOUBLE NULL,
    `prcgrp2` DOUBLE NULL,
    `prcgrp3` DOUBLE NULL,
    `prcgrp4` DOUBLE NULL,
    `prcgrp5` DOUBLE NULL,
    `prcgrp6` DOUBLE NULL,
    `prcgrp7` DOUBLE NULL,
    `prcgrp8` DOUBLE NULL,
    `creadopor` VARCHAR(254) NULL,
    `modifpor` VARCHAR(254) NULL,
    `margenpor` VARCHAR(254) NULL,
    `costo_ant` DOUBLE NULL,
    `costo_prom` DOUBLE NULL,
    `impuesto1` DOUBLE NULL,
    `impuesto2` DOUBLE NULL,
    `impuesto3` DOUBLE NULL,
    `impuesto4` DOUBLE NULL,
    `impuesto5` DOUBLE NULL,
    `impuesto6` DOUBLE NULL,
    `rutafoto` VARCHAR(254) NULL,
    `detalles` LONGTEXT NULL,
    `contraindi` LONGTEXT NULL,
    `usointerno` DOUBLE NULL,
    `aux1` DOUBLE NULL,
    `aux2` DOUBLE NULL,
    `aux3` DOUBLE NULL,
    `simbolo` VARCHAR(254) NULL,
    `modelo` VARCHAR(254) NULL,
    `discont` DOUBLE NULL,
    `flotante` DOUBLE NULL,
    `cimpuesto1` DOUBLE NULL,
    `cimpuesto2` DOUBLE NULL,
    `cimpuesto3` DOUBLE NULL,
    `cimpuesto4` DOUBLE NULL,
    `cimpuesto5` DOUBLE NULL,
    `cimpuesto6` DOUBLE NULL,
    `fechacrea` DATE NULL,
    `cuentacont` VARCHAR(254) NULL,
    `metodo` DOUBLE NULL,
    `sevence` DOUBLE NULL,
    `usalotes` DOUBLE NULL,
    `controlado` DOUBLE NULL,
    `volumen` DOUBLE NULL,
    `peso` DOUBLE NULL,
    `diametro` VARCHAR(254) NULL,
    `usabalanza` DOUBLE NULL,
    `topeminvent` DOUBLE NULL,
    `topemaxvent` DOUBLE NULL,
    `forma` VARCHAR(254) NULL,
    `esvehiculo` DOUBLE NULL,
    `aceptadscto` DOUBLE NULL,
    `aceptacred` DOUBLE NULL,
    `metodoround` DOUBLE NULL,
    `unidinamica` DOUBLE NULL,
    `campo1` VARCHAR(254) NULL,
    `campo2` VARCHAR(254) NULL,
    `campo3` VARCHAR(254) NULL,
    `campo4` VARCHAR(254) NULL,
    `campo5` VARCHAR(254) NULL,
    `campo6` VARCHAR(254) NULL,
    `campo7` VARCHAR(254) NULL,
    `campo8` VARCHAR(254) NULL,
    `campo9` VARCHAR(254) NULL,
    `campo10` VARCHAR(254) NULL,
    `imp_naciona` DOUBLE NULL,
    `imp_producc` DOUBLE NULL,
    `gimp_nacion` DOUBLE NULL,
    `gimp_produc` DOUBLE NULL,
    `ctacontinv` VARCHAR(254) NULL,
    `ctacontcost` VARCHAR(254) NULL,
    `ctacontingr` VARCHAR(254) NULL,
    `blocked` DOUBLE NULL,
    `usatallacol` DOUBLE NULL,
    `deposito_in` VARCHAR(254) NULL,
    `deposito_ou` VARCHAR(254) NULL,
    `und_simplea` DOUBLE NULL,
    `usa_servido` INTEGER NULL,
    `artcolor` DOUBLE NULL,
    `para_web` DOUBLE NULL,
    `rotacionvta` DOUBLE NULL,
    `ctacontdevo` VARCHAR(254) NULL,
    `secompra` DOUBLE NULL,
    `dadicart01` VARCHAR(254) NULL,
    `dadicart02` VARCHAR(254) NULL,
    `dadicart03` VARCHAR(254) NULL,
    `discontc` DOUBLE NULL,
    `codarancel` VARCHAR(254) NULL,
    `recargast` INTEGER NULL,
    `exislr` INTEGER NULL,
    `fechamodifi` DATE NULL,
    `esdinamico` INTEGER NULL,
    `usa_escala` INTEGER NULL,
    `usacanjepun` INTEGER NULL,
    `usabulto` INTEGER NULL,
    `cantbulto` DOUBLE NULL,
    `nousaweb` DOUBLE NULL,
    `codcont_cmx` VARCHAR(254) NULL,
    `ctacontdevc` VARCHAR(254) NULL,
    `garantiac` DOUBLE NULL,
    `hashtag` LONGTEXT NULL,
    `ctacontdesc` VARCHAR(254) NULL,
    `codigotipom` VARCHAR(254) NULL,
    `codigotipop` VARCHAR(254) NULL,
    `datos_xml` LONGTEXT NULL,
    `formato2` VARCHAR(254) NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `conceptos_fijos_tipo_socio` (
    `vista` VARCHAR(254) NULL,
    `codigo` VARCHAR(254) NULL,
    `codigoart` VARCHAR(254) NULL,
    `fch_vig` DATE NULL,
    `mto_cpto` DOUBLE NULL,
    `ptj_mora` DOUBLE NULL,
    `mto_mora` DOUBLE NULL,
    `art_mora` VARCHAR(254) NULL,
    `ult_pago` DOUBLE NULL,
    `acceso` DOUBLE NULL,
    `edad_lim` DOUBLE NULL,
    `ptj_inc_eda` DOUBLE NULL,
    `edad_desde` DOUBLE NULL,
    `codcliente` VARCHAR(254) NULL,
    `aplica_mtov` DOUBLE NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `familiares` (
    `codigo_socios` VARCHAR(254) NULL,
    `codigo_familiares` VARCHAR(254) NULL,
    `nombre` VARCHAR(254) NULL,
    `rutafoto` VARCHAR(254) NULL,
    `fechanac` DATE NULL,
    `codigo_parentesco` VARCHAR(254) NULL,
    `cedula` VARCHAR(254) NULL,
    `fvence` DATE NULL,
    `direccion` VARCHAR(254) NULL,
    `telefono_movil` VARCHAR(254) NULL,
    `email` VARCHAR(254) NULL,
    `cod` VARCHAR(254) NULL,
    `carnet` VARCHAR(254) NULL,
    `feemicrnt` DATE NULL,
    `fevnccrnt` DATE NULL,
    `foto` VARCHAR(254) NULL,
    `sexo` BIGINT NULL,
    `estatus` INTEGER NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `grupos` (
    `codigo` VARCHAR(254) NULL,
    `nombre` VARCHAR(254) NULL,
    `tcantidad` DOUBLE NULL,
    `tfacturado` DOUBLE NULL,
    `usatalla` DOUBLE NULL,
    `usacolor` DOUBLE NULL,
    `prcutil` DOUBLE NULL,
    `descuento` DOUBLE NULL,
    `formato` VARCHAR(254) NULL,
    `ctacontinv` VARCHAR(254) NULL,
    `ctacontcost` VARCHAR(254) NULL,
    `ctacontingr` VARCHAR(254) NULL,
    `oculto_rest` DOUBLE NULL,
    `noaplicarec` DOUBLE NULL,
    `formato2` VARCHAR(254) NULL,
    `grpcolor` DOUBLE NULL,
    `hereda_prop` DOUBLE NULL,
    `imp_mto_cmd` DOUBLE NULL,
    `imp_mto_cmd1` DOUBLE NULL,
    `delimitador` VARCHAR(254) NULL,
    `longitud_co` DOUBLE NULL,
    `ctacontdevo` VARCHAR(254) NULL,
    `rutafoto` VARCHAR(254) NULL,
    `nombre_cort` VARCHAR(254) NULL,
    `prcarancel` DOUBLE NULL,
    `eslicores` INTEGER NULL,
    `fechamodifi` DATE NULL,
    `ctacontdevc` VARCHAR(254) NULL,
    `codcont_cmx` VARCHAR(254) NULL,
    `referencia` VARCHAR(254) NULL,
    `nousaweb` DOUBLE NULL,
    `notas` LONGTEXT NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `mae_ultimo_pago` (
    `tipodoc` VARCHAR(254) NULL,
    `documento` VARCHAR(254) NULL,
    `fechadoc` DATE NULL,
    `codcliente` VARCHAR(254) NULL,
    `emision` DATE NULL,
    `codigo` VARCHAR(254) NULL,
    `pid` VARCHAR(254) NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `parentesco_familiares` (
    `codigo` VARCHAR(254) NULL,
    `nombre` VARCHAR(254) NULL,
    `carnet` VARCHAR(254) NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `socios` (
    `codigo` VARCHAR(254) NULL,
    `nombre` VARCHAR(254) NULL,
    `cedula` VARCHAR(254) NULL,
    `nrorif` VARCHAR(254) NULL,
    `nronit` VARCHAR(254) NULL,
    `referenc1` VARCHAR(254) NULL,
    `referenc2` VARCHAR(254) NULL,
    `direccion` VARCHAR(254) NULL,
    `telefonos` VARCHAR(254) NULL,
    `numerofax` VARCHAR(254) NULL,
    `fecha` DATE NULL,
    `perscont` VARCHAR(254) NULL,
    `estatus` DOUBLE NULL,
    `nota` VARCHAR(254) NULL,
    `email` VARCHAR(254) NULL,
    `wwwcli` VARCHAR(254) NULL,
    `tipo` VARCHAR(254) NULL,
    `direccobro` LONGTEXT NULL,
    `direcenvio` LONGTEXT NULL,
    `sexo` BIGINT NULL,
    `nacionalida` VARCHAR(254) NULL,
    `fechanac` DATE NULL,
    `edocivil` DOUBLE NULL,
    `telhabitaci` VARCHAR(254) NULL,
    `celular` VARCHAR(254) NULL,
    `trabempresa` VARCHAR(254) NULL,
    `trabtelefon` VARCHAR(254) NULL,
    `telefono_movil` VARCHAR(254) NULL,
    `carnet` VARCHAR(254) NULL,
    `feemicrnt` DATE NULL,
    `fevnccrnt` DATE NULL,
    `foto` VARCHAR(254) NULL,
    `exonerado` BIGINT NULL,
    `fch_exon` DATE NULL,
    `fin` DATE NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `suspensiones_familiares` (
    `idsus` INTEGER NULL,
    `codigo` VARCHAR(254) NULL,
    `Nombreyapelllido` VARCHAR(254) NULL,
    `fch_suspen` DATE NULL,
    `dias` INTEGER NULL,
    `fch_vcto` DATE NULL,
    `cod_mot` VARCHAR(254) NULL,
    `notas` LONGTEXT NULL,
    `Actjunta` INTEGER NULL,
    `ActTD` INTEGER NULL,
    `status` INTEGER NULL,
    `ingreso` DATE NULL,
    `cedula` VARCHAR(254) NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `suspensiones_motivos` (
    `cod_mot` VARCHAR(254) NULL,
    `descr` VARCHAR(254) NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `suspensiones_socios` (
    `idsus` INTEGER NULL,
    `codigo` VARCHAR(254) NULL,
    `Nombreyapelllido` VARCHAR(254) NULL,
    `fch_suspen` DATE NULL,
    `dias` INTEGER NULL,
    `fch_vcto` DATE NULL,
    `cod_mot` VARCHAR(254) NULL,
    `notas` LONGTEXT NULL,
    `Actjunta` INTEGER NULL,
    `ActTD` INTEGER NULL,
    `status` INTEGER NULL,
    `ingreso` DATE NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tipo_socio` (
    `codigo` VARCHAR(254) NULL,
    `nombre` VARCHAR(254) NULL,
    `codigocont` VARCHAR(254) NULL,
    `carnet` VARCHAR(254) NULL,
    `codcontcaja` VARCHAR(254) NULL,
    `predeter` DOUBLE NULL,
    `nousaweb` DOUBLE NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

